### ISSUE TITLE
Error intercepting tombstone warning

### ISSUE THREAD

**Issue by dipanshah-continuum** [datastax/metric-collector-for-apache-cassandra#12]
This is for Cassandra V 3.11.3.

WARN  [ReadStage-9] 2020-05-27 05:38:34,503 ReadCommand.java:569 - Read 251 live rows and 2387 tombstone cells for query SELECT * FROM keyspace.table WHERE column1, column2 = xxx, xxx LIMIT 5000 (see tombstone_warn_threshold)
ERROR [ReadStage-9] 2020-05-27 05:38:34,504 TombstoneWarningInterceptor.java:94 - Error intercepting tombstone warning message:
java.lang.reflect.InvocationTargetException: null
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_252]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_252]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_252]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_252]
        at com.datastax.mcac.interceptors.TombstoneWarningInterceptor.warn(TombstoneWarningInterceptor.java:68) ~[datastax-mcac-agent.jar:na]
        at org.apache.cassandra.service.ClientWarn.warn(ClientWarn.java) [apache-cassandra-3.11.3.jar:3.11.3]
        at org.apache.cassandra.db.ReadCommand$1MetricRecording.onClose(ReadCommand.java:568) [apache-cassandra-3.11.3.jar:3.11.3]
        at org.apache.cassandra.db.transform.BasePartitions.runOnClose(BasePartitions.java:70) [apache-cassandra-3.11.3.jar:3.11.3]
        at org.apache.cassandra.db.transform.BaseIterator.close(BaseIterator.java:86) [apache-cassandra-3.11.3.jar:3.11.3]
        at org.apache.cassandra.db.ReadCommandVerbHandler.doVerb(ReadCommandVerbHandler.java:51) [apache-cassandra-3.11.3.jar:3.11.3]
        at org.apache.cassandra.net.MessageDeliveryTask.run(MessageDeliveryTask.java:66) [apache-cassandra-3.11.3.jar:3.11.3]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_252]
        at org.apache.cassandra.concurrent.AbstractLocalAwareExecutorService$FutureTask.run(AbstractLocalAwareExecutorService.java:162) [apache-cassandra-3.11.3.jar:3.11.3]
        at org.apache.cassandra.concurrent.AbstractLocalAwareExecutorService$LocalSessionFutureTask.run(AbstractLocalAwareExecutorService.java:134) [apache-cassandra-3.11.3.jar:3.11.3]
        at org.apache.cassandra.concurrent.SEPWorker.run(SEPWorker.java:109) [apache-cassandra-3.11.3.jar:3.11.3]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_252]
Caused by: org.apache.cassandra.exceptions.SyntaxException: line 1:65 no viable alternative at input ',' (...* FROM keyspace.table WHERE [column1],...)
        at org.apache.cassandra.cql3.ErrorCollector.throwFirstSyntaxError(ErrorCollector.java:101) ~[apache-cassandra-3.11.3.jar:3.11.3]
        at org.apache.cassandra.cql3.CQLFragmentParser.parseAnyUnhandled(CQLFragmentParser.java:80) ~[apache-cassandra-3.11.3.jar:3.11.3]
        at org.apache.cassandra.cql3.QueryProcessor.parseStatement(QueryProcessor.java:587) ~[apache-cassandra-3.11.3.jar:3.11.3]
        ... 16 common frames omitted

**Comment by tjake** [comment]
Thank you for the report!

Can you explain the actual query running here? I think the issue is the ReadCommand back to CQL is not valid CQL.

**Comment by dipanshah-continuum** [comment]
Hi tjake,

The query works perfectly fine. I dont know why it is printed in the logs like this but the actual query is:
 SELECT * FROM keyspace.table WHERE column1 = xxx, and column2 = xxx LIMIT 5000;

Also the query is successfully getting executed from the application and we are not getting any errors for that,

**Comment by jmooo** [comment]
Just installed MCAC v0.1.11 with Cassandra v3.11.6 and the same error is popping up in my C* logs now as well:

>WARN  [ReadStage-2] 2020-07-22 18:23:10,973 ReadCommand.java:569 - Read 1821 live rows and 3642 tombstone cells for query SELECT * FROM chaindata.transaction WHERE ... LIMIT 5000 (see tombstone_warn_threshold)
>ERROR [ReadStage-2] 2020-07-22 18:23:10,973 TombstoneWarningInterceptor.java:94 - Error intercepting tombstone warning message:
>java.lang.reflect.InvocationTargetException: null
