### ISSUE TITLE
java.lang.NoSuchFieldError: FAIL_ON_TRAILING_TOKENS

### ISSUE THREAD

**Issue by phanirajl** [datastax/metric-collector-for-apache-cassandra#14]
Hi @tjake @bradfordcp @driftx 
       I'm getting below error after adding the jar and bouncing the node back . i tried all three below versions. 
datastax-mcac-agent-0.1.10
datastax-mcac-agent-0.1.9
datastax-mcac-agent-0.1.8

INFO  [CompactionExecutor:2] 2020-06-12 18:47:58,636 CompactionEndedInterceptor.java:71 - Problem collection compaction end report
java.lang.NoSuchFieldError: FAIL_ON_TRAILING_TOKENS
	at com.datastax.mcac.utils.JacksonUtil.lambda$static$0(JacksonUtil.java:52) ~[datastax-mcac-agent.jar:na]
	at com.google.common.base.Suppliers$MemoizingSupplier.get(Suppliers.java:125) ~[guava-18.0.jar:na]
	at com.datastax.mcac.utils.JacksonUtil.getObjectMapper(JacksonUtil.java:80) ~[datastax-mcac-agent.jar:na]
	at com.datastax.mcac.utils.JacksonUtil.writeValueAsString(JacksonUtil.java:296) ~[datastax-mcac-agent.jar:na]
	at com.datastax.mcac.UnixSocketClient.report(UnixSocketClient.java:1406) ~[datastax-mcac-agent.jar:na]
	at com.datastax.mcac.interceptors.CompactionEndedInterceptor.intercept(CompactionEndedInterceptor.java:65) ~[datastax-mcac-agent.jar:na]
	at org.apache.cassandra.db.compaction.CompactionIterator.getMergedRowCounts(CompactionIterator.java) [apache-cassandra-3.11.2.jar:3.11.2]
	at org.apache.cassandra.db.compaction.CompactionTask.runMayThrow(CompactionTask.java:227) [apache-cassandra-3.11.2.jar:3.11.2]
	at org.apache.cassandra.utils.WrappedRunnable.run(WrappedRunnable.java:28) [apache-cassandra-3.11.2.jar:3.11.2]
	at org.apache.cassandra.db.compaction.CompactionTask.executeInternal(CompactionTask.java:85) [apache-cassandra-3.11.2.jar:3.11.2]
	at org.apache.cassandra.db.compaction.AbstractCompactionTask.execute(AbstractCompactionTask.java:61) [apache-cassandra-3.11.2.jar:3.11.2]
	at org.apache.cassandra.db.compaction.CompactionManager$BackgroundCompactionCandidate.run(CompactionManager.java:275) [apache-cassandra-3.11.2.jar:3.11.2]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_232]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_232]
	at org.apache.cassandra.concurrent.NamedThreadFactory.lambda$threadLocalDeallocator$0(NamedThreadFactory.java:81) [apache-cassandra-3.11.2.jar:3.11.2]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_232]

**Comment by phanirajl** [comment]
@tjake
