### ISSUE TITLE
ArrayIndexOutOfBoundsException when running with Cassandra 3.11.9

### ISSUE THREAD

**Issue by rtib** [datastax/metric-collector-for-apache-cassandra#24]
After upgrading to Apache Cassandra 3.11.9 and metric-collector-for-apache-cassandra 0.1.12, Cassandra is continuous logging the below Error for 

```
Nov 09 14:47:20 <hostname> cassandra[18966]: WARN  [insights-3-1] 2020-11-09 14:47:20,548 UnixSocketClient.java:830 - Error reporting:
Nov 09 14:47:20 <hostname> cassandra[18966]: java.lang.ArrayIndexOutOfBoundsException: 115
Nov 09 14:47:20 <hostname> cassandra[18966]:         at org.apache.cassandra.metrics.TableMetrics.combineHistograms(TableMetrics.java:261) ~[apache-cassandra-3.11.9.jar:3.11.9]
Nov 09 14:47:20 <hostname> cassandra[18966]:         at org.apache.cassandra.metrics.TableMetrics.access$000(TableMetrics.java:48) ~[apache-cassandra-3.11.9.jar:3.11.9]
Nov 09 14:47:20 <hostname> cassandra[18966]:         at org.apache.cassandra.metrics.TableMetrics$11.getValue(TableMetrics.java:376) ~[apache-cassandra-3.11.9.jar:3.11.9]
Nov 09 14:47:20 <hostname> cassandra[18966]:         at org.apache.cassandra.metrics.TableMetrics$11.getValue(TableMetrics.java:373) ~[apache-cassandra-3.11.9.jar:3.11.9]
Nov 09 14:47:20 <hostname> cassandra[18966]:         at com.datastax.mcac.UnixSocketClient.writeMetric(UnixSocketClient.java:839) [datastax-mcac-agent.jar:na]
Nov 09 14:47:20 <hostname> cassandra[18966]:         at com.datastax.mcac.UnixSocketClient.access$700(UnixSocketClient.java:78) [datastax-mcac-agent.jar:na]
Nov 09 14:47:20 <hostname> cassandra[18966]:         at com.datastax.mcac.UnixSocketClient$2.lambda$onGaugeAdded$0(UnixSocketClient.java:626) ~[datastax-mcac-agent.jar:na]
Nov 09 14:47:20 <hostname> cassandra[18966]:         at com.datastax.mcac.UnixSocketClient.writeGroup(UnixSocketClient.java:819) [datastax-mcac-agent.jar:na]
Nov 09 14:47:20 <hostname> cassandra[18966]:         at com.datastax.mcac.UnixSocketClient.lambda$restartMetricReporting$2(UnixSocketClient.java:798) [datastax-mcac-agent.jar:na]
Nov 09 14:47:20 <hostname> cassandra[18966]:         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_202]
Nov 09 14:47:20 <hostname> cassandra[18966]:         at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:126) ~[netty-all-4.0.44.Final.jar:4.0.44.Final]
Nov 09 14:47:20 <hostname> cassandra[18966]:         at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:399) ~[netty-all-4.0.44.Final.jar:4.0.44.Final]
Nov 09 14:47:20 <hostname> cassandra[18966]:         at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:307) ~[netty-all-4.0.44.Final.jar:4.0.44.Final]
Nov 09 14:47:20 <hostname> cassandra[18966]:         at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131) ~[netty-all-4.0.44.Final.jar:4.0.44.Final]
Nov 09 14:47:20 <hostname> cassandra[18966]:         at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144) ~[netty-all-4.0.44.Final.jar:4.0.44.Final]
Nov 09 14:47:20 <hostname> cassandra[18966]:         at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_202]
```

**Comment by rtib** [comment]
This seems to be related to, possibly caused by [CASSANDRA-16259](https://issues.apache.org/jira/browse/CASSANDRA-16259).

**Comment by rtib** [comment]
It was the Cassandra issue mentioned above.
