### ISSUE TITLE
Cannot Run the Datastack metrics collector

### ISSUE THREAD

**Issue by DanMan259** [datastax/metric-collector-for-apache-cassandra#33]
I implemented the metrics collector on Cassandra 3.11 and got the following log on startup.

Running on RHEL 7, and ppc64le architecture.

```
INFO [main] 2021-01-18 23:19:58,353 CassandraDaemonInterceptor.java:61 - Starting DataStax Metric Collector for Apache Cassandra 0.1.13
ERROR [main] 2021-01-18 23:19:58,355 CassandraDaemon.java:774 - Exception encountered during startup
java.lang.AssertionError: null
	at com.datastax.mcac.UnixSocketClient.epollGroup(UnixSocketClient.java:235) ~[datastax-mcac-agent.jar:na]
	at com.datastax.mcac.UnixSocketClient.start(UnixSocketClient.java:289) ~[datastax-mcac-agent.jar:na]
	at com.datastax.mcac.interceptors.CassandraDaemonInterceptor.intercept(CassandraDaemonInterceptor.java:62) ~[datastax-mcac-agent.jar:na]
	at org.apache.cassandra.service.CassandraDaemon.start(CassandraDaemon.java) [apache-cassandra-3.11.6.jar:3.11.6]
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:645) [apache-cassandra-3.11.6.jar:3.11.6]
	at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:757) [apache-cassandra-3.11.6.jar:3.11.6]
INFO [StorageServiceShutdownHook] 2021-01-18 23:19:58,358 HintsService.java:209 - Paused hints dispatch
INFO [StorageServiceShutdownHook] 2021-01-18 23:19:58,362 Server.java:179 - Stop listening for CQL clients
INFO [StorageServiceShutdownHook] 2021-01-18 23:19:58,362 Gossiper.java:1647 - Announcing shutdown

```

**Comment by sri-postgres-cassandra** [comment]
I am facing same issue, can you please let me know if you were able to solve this issue

**Comment by jsanda** [comment]
@sri-postgres-cassandra What OS/arch are you running on?

**Comment by jdonenine** [comment]
For reference we found a similar issue in some work we were doing on the management-api where epoll wasn't available on MacOS:  https://github.com/k8ssandra/management-api-for-apache-cassandra/issues/128
